In [24]:
class Employee:
    emp_count = 0
    def __init__(self,name,family,salary,department):
        self.Name = name
        self.Family = family
        self.Salary = salary
        self.Department = department
        Employee.emp_count += 1
    def average_salary(employees):
        sum = 0
        for employee in employees:
            sum += employee.Salary
        return sum / Employee.emp_count
    
class FulltimeEmployee(Employee):

    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)

    def year_end_bonus(self):
        print("Year end bonus is provided for full time employees.")

def main():
    employees = []
    e1 = FulltimeEmployee("Bob", "william", 6000, "CS")
    e2 = FulltimeEmployee("Mary", "Thomas", 8529.486, "IT")
    e3 = FulltimeEmployee("Harry", "Potter", 1596, "Management")
    
    e1.year_end_bonus()
    employees.append(e1)
    employees.append(e2)
    employees.append(e3)
    print("Average salary:", FulltimeEmployee.average_salary(employees))


if __name__ == "__main__":
    main()

Year end bonus is provided for full time employees.
Average salary: 5375.162


Created a class named Employee and created a data member named emp_count to count the number of employees. Constuctor has been created to initialize parameters. average_salary funtion is created and employees list is passed as an argument to calculate average salary. Full_Time_Employee class has been created that extends the properties of Employee class. average_salary function is called by creating the object for Full_Time_Employee class.

In [30]:
# importing numpy
import numpy as np
a = np.random.uniform(1,20,20)
print(a)

array = a;
print("Array : " + str(array))
n = array.size

N = 4
M = n//N

# reshaping numpy array
# converting it to 2-D from 1-D array
reshaped = array.reshape((N, M))

# printing reshaped array
print("First Reshaped Array 4 x 5 : ")
print(reshaped)

a = reshaped
b = a
b[np.arange(len(a)), a.argmax(1)] = 0
print(b)

[12.29273843 19.14352549 17.24211103 14.10520718  6.54700755 13.35664542
  8.02423485 15.36756527  7.02907949 14.28574225  3.16548157 18.12041389
 14.03169892  2.43636636  7.62944501  7.61706842 15.94473712 15.92060213
 15.5436494   3.0608058 ]
Array : [12.29273843 19.14352549 17.24211103 14.10520718  6.54700755 13.35664542
  8.02423485 15.36756527  7.02907949 14.28574225  3.16548157 18.12041389
 14.03169892  2.43636636  7.62944501  7.61706842 15.94473712 15.92060213
 15.5436494   3.0608058 ]
First Reshaped Array 4 x 5 : 
[[12.29273843 19.14352549 17.24211103 14.10520718  6.54700755]
 [13.35664542  8.02423485 15.36756527  7.02907949 14.28574225]
 [ 3.16548157 18.12041389 14.03169892  2.43636636  7.62944501]
 [ 7.61706842 15.94473712 15.92060213 15.5436494   3.0608058 ]]
[[12.29273843  0.         17.24211103 14.10520718  6.54700755]
 [13.35664542  8.02423485  0.          7.02907949 14.28574225]
 [ 3.16548157  0.         14.03169892  2.43636636  7.62944501]
 [ 7.61706842  0.         15.9

Imported numpy library and A vector has been created with random values of size 20 with range between 1 to 20. Array is reshaped to size of rows and columns of 4 and 5 using reshape method. Maximum element of each row of array is replaced with zero.